apiVersion: v1
kind: Service
metadata:
  name: my-web-service
spec:
  type: NodePort
  selector:
    app: web
  ports:
    - port: 80          # Service port inside Kubernetes
      targetPort: 8080  # Application port inside the Pod
      nodePort: 30080   # External port on each cluster Node
